### ISSUE TITLE
error when building npm 

### ISSUE THREAD

**Issue by rikrdo89** [4dn-dcic/react-workflow-viz#37]
I get the following errors, and index.html loads but graph is unintelligible. 
```
Writing to ./dist/react-workflow-viz.min.css
[Error: ENOENT: no such file or directory, open './dist/react-workflow-viz.min.css'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './dist/react-workflow-viz.min.css'
}
[Error: ENOENT: no such file or directory, open './dist/react-workflow-viz.min.css.map'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './dist/react-workflow-viz.min.css.map'
}
```

**Comment by Bianca-Morris** [comment]
Hi! Looks like it's been a few months since you made this post. If you've resolved it, let me know and I'll close this issue. If you're still having this problem, please provide more context, and I'll try to assist. To start, what release/version are you using? Could also be useful to know your node and npm versions. I'm assuming you're trying to run the demo files in the `react-workflow-viz` repo; is this correct?

**Comment by Bianca-Morris** [comment]
There hasn't been any update to this issue in over a year; closing this issue. Please open a new one, if your issue persists.
