### ISSUE TITLE
On production, demo>test folder is not watched

### ISSUE THREAD

**Issue by rikrdo89** [4dn-dcic/react-workflow-viz#38]
I added a new files under the demo>test folder, but  it is not shown in the website during production.

**Comment by Bianca-Morris** [comment]
Hi! Looks like it's been a few months since you made this post, but in case you are curious: this is actually expected behavior. The "watching" behavior is limited to the `/src/` folder, so that developers and contributors can update the visualization source code a little more easily. And it doesn't work in the production build (`npm run build` in `index.html`); only in the dev build (`npm run dev`, on `localhost:8100`).

The project isn't really ready to be used by the general public, so we don't have any public-facing documentation at the moment. If you have a bit of data that you want to try out in the local demo build, you probably can do that, but it will take a lot of work. You'll have to take a look at the data structure we're expecting (again, there's no doc for this, really -- so you'd have to just look through the example jsons) and transform your data into that general structure. Then you can put your JSON into the `demo/testdata` folder and then add a new object to the testData array in line 21 of the `demo.js` file. Then your new item would show up in the dropdown and you would be able to see a visualization of your data.

We can't provide support for this right now, unfortunately. So you'd be on your own to figure it out.
